apps/dashboard/urls.py
from django.conf.urls import patterns, url, include

import views

urlpatterns = patterns(
    '',
    url(r'^$', views.DashboardHomeView.as_view(), name='dashboard_home'),
    url(r'^paciente/', include('pacientes.urls', namespace='paciente')),
    url(r'^paciente/', include('embarazos.urls', namespace='embarazos')),
    url(r'^paciente/', include('controles.urls', namespace='controles')),
    url(
        r'^reportes-estadisticos/',
        include('indicadores.urls', namespace='indicadores')),
    url(r'^citas/', include('citas.urls', namespace='cita')),
    url(
        r'^establecimientos/',
        include('establecimientos.urls', namespace='establecimientos')),
)

apps/embarazos/urls.py
from django.conf.urls import patterns, url, include

import views

reports = patterns(
    '',
    url(r'^ficha-tamizaje/(?P<embarazo_id>\d+)/$',
        views.FichaTamizajeReportView.as_view(),
        name='ficha_tamizaje'),
    url(r'^ficha-tamizaje/(?P<embarazo_id>\d+)/(?P<accion_id>\d+)/$',
        views.FichaTamizajeReportView.as_view(),
        name='ficha_tamizaje'),
    url(r'^tamizaje-depresion/(?P<embarazo_id>\d+)/$',
        views.TamizajeDepresionReportView.as_view(),
        name='tamizaje_depresion'),
)

urlpatterns = patterns(
    '',
    url(r'^reportes/',
        include(reports, namespace='reports')),
    url(r'^(?P<paciente_id>\d+)/embarazos-previos/$',
        views.UltimosEmbarazosView.as_view(),
        name='ultimos_embarazos'),
    url(r'^(?P<paciente_id>\d+)/ecografias/$',
        views.EcografiasView.as_view(),
        name='ecografias'),
    url(r'^(?P<paciente_id>\d+)/agregar-ecografia/$',
        views.EcografiaCreateView.as_view(),
        name='ecografia_create'),
    url(r'^(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/editar/$',
        views.EcografiaUpdateView.as_view(),
        name='ecografia_edit'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo-previo/$',
        views.UltimoEmbarazoCreateView.as_view(),
        name='ultimo_embarazo_create'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/$',
        views.UltimoEmbarazoUpdateView.as_view(),
        name='ultimo_embarazo_edit'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/eliminar/$',
        views.UltimoEmbarazoDeleteView.as_view(),
        name='ultimo_embarazo_delete'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo/$',
        views.EmbarazoCreateView.as_view(),
        name='create'),
    url(r'^(?P<paciente_id>\d+)/registrar-control-embarazo/$',
        views.EmbarazoControlCreateView.as_view(),
        name='create-control-embarazo'),
    url(r'^(?P<paciente_id>\d+)/editar-embarazo-actual/$',
        views.EmbarazoUpdateCurrentView.as_view(),
        name='update_current'),
    url(r'^plan-de-parto/(?P<embarazo_id>\d+)/$',
        views.PlanPartoView.as_view(),
        name='plan_parto'),
    url(r'^plan-de-parto/(?P<embarazo_id>\d+)/edit/$',
        views.PlanPartoUpdateView.as_view(),
        name='plan_parto_edit'),
    url(r'^(?P<paciente_id>\d+)/terminar-embarazo/(?P<embarazo_id>\d+)/$',
        views.TerminarEmbarazoView.as_view(),
        name='terminar_embarazo'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo-previo'
        r'/embarazo/(?P<embarazo_id>\d+)/$',
        views.UltimoEmbarazoFromEmbarazoCreateView.as_view(),
        name='ultimo_embarazo_from_embarazo_create'),
    url(r'^(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/eliminar/$',
        views.EcografiaDeleteView.as_view(),
        name='ecografia_delete'),
    url(r'^(?P<paciente_id>\d+)/editar-violencia-genero/$',
        views.ViolenciaGeneroUpdateCurrentView.as_view(),
        name='violencia_update'),
)

apps/pacientes/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns(
    '',
    url(
        r'^(?P<id>\d+)/$',
        views.PacienteDetailView.as_view(),
        name='detail'),
    url(
        r'^(?P<id>\d+)/editar/$',
        views.PacienteUpdateView.as_view(),
        name='update'),
    url(
        r'^(?P<id>\d+)/editar-control/$',
        views.PacienteControlUpdateView.as_view(),
        name='update_control'),
    url(
        r'^(?P<id>\d+)/antecedentes/$',
        views.PacienteAntecedentesDetailView.as_view(),
        name='antecedentes'),
    url(
        r'^(?P<id>\d+)/control-antecedentes/$',
        views.PacienteControlAntecedentesDetailView.as_view(),
        name='control_antecedentes'),
    url(
        r'^(?P<id>\d+)/antecedentes/editar/$',
        views.PacienteAntecedentesUpdateView.as_view(),
        name='antecedentes_edit'),
    url(
        r'^(?P<id>\d+)/control-antecedentes/editar/$',
        views.PacienteControlAntecedentesUpdateView.as_view(),
        name='control_antecedentes_edit'),
    url(
        r'^(?P<id>\d+)/antecedentes-familiares/$',
        views.AntecedentesFamiliaresView.as_view(),
        name='antecedentes_familiares_edit'),
    url(
        r'^(?P<id>\d+)/antecedentes-medicos/$',
        views.AntecedentesMedicosView.as_view(),
        name='antecedentes_medicos_edit'),
    url(
        r'^(?P<id>\d+)/antecedentes-resume-json',
        views.AntecedentesResumeJsonView.as_view(),
        name='antecedentes_resume_json'),
    url(
        r'^(?P<paciente_id>\d+)/crear-historia-clinica/$',
        views.HistoriaClinicaCreateView.as_view(),
        name='historia_clinica_create'),
    url(
        r'^registro/$',
        views.PacienteCreateView.as_view(),
        name='create'),
    url(
        r'^buscar/$',
        views.PacienteSearchView.as_view(),
        name='search'),
    url(
        r'^crear/(?P<id>\d+)$',
        views.PacienteCreateForce.as_view(),
        name='create_force'),
url(
        r'^crear-paciente-control/(?P<id>\d+)$',
        views.PacienteCreateForceUpdate.as_view(),
        name='create_force_update'),
)

apps/partos/urls.py
from django.conf.urls import patterns, url, include

import views

reports = patterns(
    '',
    url(r'^partograma/(?P<partograma_id>\d+)/pdf/$',
        views.PartogramaReportView.as_view(), name='partograma_pdf'),
    url(r'^partograma/(?P<partograma_id>\d+)/grafica-controles-vitales/pdf/$',
        views.GraficaControlesVitalesView.as_view(
        ), name='grafica_controles_vitales'),
    url(r'^hoja-de-monitoreo-materno-fetal/(?P<partograma_id>\d+)/$',
        views.HojaMonitoreoMaternoFetalReportView.as_view(), name='hoja_monitoreo_materno_fetal'),
    url(r'^partos-historia-clinica/(?P<embarazo_id>\d+)/$',
        views.PartosHistoriaClinicaReportView.as_view(), name='partos_historia_clinica'),
    url(r'^partos-controles-prenatal/(?P<embarazo_id>\d+)/$',
        views.PartosControlesPrenatalReportView.as_view(), name='partos_controles_prenatal'),
    url(r'^partograma/resumen-pdf/$', views.ResumenPartoReportView.as_view(), name='parto_pdf'),
    url(r'^partograma/partograma-pdf/$', views.PartogramaHomeReportView.as_view(), name='partograma_home_pdf'),
)

urlpatterns = patterns(
    '',
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^reportes/', include(reports, namespace='reports')),
    url(r'^registrar-ingreso/(?P<paciente_id>\d+)/$', views.IngresoCreateView.as_view(), name='ingreso_register'),
    url(r'^ingreso/(?P<ingreso_id>\d+)/editar/$', views.IngresoUpdateView.as_view(), name='ingreso_edit'),
    url(r'^paciente/(?P<id>\d+)/$', views.PPacienteDetailView.as_view(), name='paciente_detail'),
    url(r'^paciente/(?P<id>\d+)/editar/$', views.PPacienteUpdateView.as_view(), name='paciente_update'),
    url(r'^paciente-control/(?P<id>\d+)/editar/$', views.PPacienteControlUpdateView.as_view(),
        name='paciente_control_update'),
    url(r'^paciente/registro/$', views.PPacienteCreateView.as_view(), name='paciente_create'),
    url(r'^paciente/crear/(?P<id>\d+)$', views.PPacienteCreateForceView.as_view(), name='paciente_create_force'),
    url(r'^paciente/(?P<id>\d+)/antecedentes/$', views.PPacienteAntecedentesDetailView.as_view(),
        name='paciente_antecedentes'),
    url(r'^paciente/(?P<id>\d+)/antecedentes/editar/$', views.PPacienteAntecedentesUpdateView.as_view(),
        name='paciente_antecedentes_edit'),
    url(r'^paciente/(?P<id>\d+)/antecedentes-familiares/$', views.PAntecedentesFamiliaresView.as_view(),
        name='paciente_antecedentes_familiares_edit'),
    url(r'^(?P<id>\d+)/antecedentes-medicos/$', views.PAntecedentesMedicosView.as_view(),
        name='paciente_antecedentes_medicos_edit'),
    url(r'^paciente/buscar/$', views.PPacienteSearchView.as_view(), name='paciente_search'),
    url(r'^(?P<paciente_id>\d+)/embarazos-previos/$', views.PUltimosEmbarazosView.as_view(),
        name='embarazos_ultimos_embarazos'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo-previo/$', views.PUltimoEmbarazoCreateView.as_view(),
        name='embarazos_ultimo_embarazo_create'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/$', views.PUltimoEmbarazoUpdateView.as_view(),
        name='embarazos_ultimo_embarazo_edit'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/eliminar/$', views.PUltimoEmbarazoDeleteView.as_view(),
        name='embarazos_ultimo_embarazo_delete'),
    url(r'^embarazo/(?P<paciente_id>\d+)/registrar-embarazo/$', views.PEmbarazoCreateView.as_view(),
        name='embarazo_create'),
    url(r'^embarazo/(?P<paciente_id>\d+)/editar-embarazo-actual/$', views.PEmbarazoUpdateCurrentView.as_view(),
        name='update_current'),
    url(r'^embarazo/(?P<paciente_id>\d+)/ecografias/$', views.PEcografiasView.as_view(), name='ecografias'),
    url(r'^embarazo/(?P<paciente_id>\d+)/agregar-ecografia/$', views.PEcografiaCreateView.as_view(),
        name='ecografia_create'),
    url(r'^embarazo/(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/editar/$', views.PEcografiaUpdateView.as_view(),
        name='ecografia_edit'),
    url(r'^embarazo/(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/eliminar/$', views.PEcografiaDeleteView.as_view(),
        name='ecografia_delete'),
    url(r'^ingreso/(?P<ingreso_id>\d+)/sintomas/edit/$', views.PSintomasView.as_view(), name='sintomas'),
    url(r'^ingreso/(?P<ingreso_id>\d+)/laboratorio/editar/$', views.PLaboratorioView.as_view(), name='laboratorio'),
    url(r'^(?P<ingreso_id>\d+)/registrar-termino-embarazo/$', views.TerminacionEmbarazoCreateView.as_view(),
        name='registrar_termino_embarazo'),
    url(r'^terminacion-embarazo/(?P<terminacion_embarazo_id>\d+)/editar/$',
        views.TerminacionEmbarazoUpdateView.as_view(
        ), name='terminacion_embarazo_edit'),
    url(r'^(?P<ingreso_id>\d+)/partograma/$',
        views.PartogramaView.as_view(), name='partograma'),
    url(r'^(?P<ingreso_id>\d+)/partograma/medicion/(?P<medicion_id>\d+)/$',
        views.PartogramaMedicionUpdateView.as_view(
        ), name='partograma_medicion'),
    url(r'^(?P<ingreso_id>\d+)/partograma/chart-data/',
        views.PartogramaChartDataView.as_view(),
        name='partograma_chart_data'),
    url(r'^ingreso/(?P<ingreso_id>\d+)/examen-fisico/editar/$',
        views.PExamenFisicoView.as_view(),
        name='examen_fisico'),
    url(r'^control/(?P<id>\d+)/ultimo-control/$',
        views.UltimoControlView.as_view(), name='ultimo_control'),
    url(r'^referidas/$', views.ReferidasView.as_view(), name='pacientes_referidas'),
)

wawared/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

handler403 = 'perfiles.views.handler_403'

admin.autodiscover()

urlpatterns = patterns(
    '',
    # Api
    url(r'^api/', include('api.urls', namespace='api')),
    # CIE
    url(r'^cie/', include('cie.urls', namespace='cie')),
    # CPT
    url(r'^cpt/', include('cpt.urls', namespace='cpt')),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Perfiles
    url(r'^', include('perfiles.urls')),
    # Dahboard
    url(r'^', include('dashboard.urls')),
    # Ubigeo
    url('^ubigeo/', include('ubigeo.urls', namespace='ubigeo')),
    # Gestantes
    url(r'^hce/', include('gestantes.urls', namespace='gestantes')),
    url(r'session_security/', include('session_security.urls')),
    # Dnireniec
    url(r'^dnireniec/', include('dnireniec.urls', namespace='dnireniec')),
    # Partos
    url(r'^partos/', include('partos.urls', namespace='partos')),
    # Firma
    url(r'^firma/', include('firma.urls', namespace='firma')),
    # Puerperio
    url(r'^puerperio/', include('puerperio.urls', namespace='puerperio')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/embarazos/templates/embarazos/partials/control_paciente_resume_header.html
{% load thumbnail %}
{% load static %}
{% load paciente_tags %}
{% url 'paciente:update' paciente.id as paciente_upd_url %}
{% url 'embarazos:create' paciente.id as create_emb_url %}
<div class="panel-body">
  <div class="row">
    <div class="col-md-2">
      {% if paciente.foto %}
        <img src="{% thumbnail paciente.foto 112x122 %}" width="112" height="112" alt="{{ paciente.nombre_completo }}" />
      {% else %}
        <img src="{% static 'img/avatar2.png' %}" width="112" height="112" alt="Imagen por defecto cuando no se muestra la foto real del paciente" />
      {% endif %}
    </div>
    <div class="col-md-10">
      <h2>
        <a style="color: gray" href="{% url 'paciente:update' paciente.id %}">{{ paciente.nombre_completo.upper }}</a>
      </h2>
      <div class="row">
        <div class="col-sm-2">
          <p>N° HC: {{ paciente|hc:request }}</p>
          {% ifequal paciente.tipo_documento paciente.DOCUMENTO_DNI_RESPONSABLE %}
            <p>DNI Responsable: {{ paciente.numero_documento }}</p>
          {% else %}
            <p>{{ paciente.nombre_documento }}: {{ paciente.numero_documento }}</p>
          {% endifequal %}
        </div>
        <div class="col-sm-2">
          <p>Edad: {{ paciente.edad }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="panel-body">
  <div class="col-sm-7 col-sm-offset-3">
    <div class="btn-group">
      <a class="btn btn-default"
          {% if paciente_upd_url == request.path %}
            style="background-color: green;color: white;"
          {% endif %}
          href="{% url 'partos:paciente_control_update' paciente.id %}">Afiliación</a>
      {% if 'pacientes.change_antecedenteginecologico' in user.get_all_permissions %}
        <a class="btn btn-default"
            {% if 'antecedente' in request.path %}
              style="background-color: green;color: white;"
            {% endif %}
            href="{% url 'paciente:control_antecedentes_edit' paciente.id %}">Antecedentes</a>
      {% else %}
        <a class="btn btn-default"
            {% if 'antecedente' in request.path %}
              style="background-color: green;color: white;"
            {% endif %}
            href="{% url 'paciente:control_antecedentes' paciente.id %}">Antecedentes</a>
      {% endif %}
      <a class="btn btn-default"
          {% if 'registrar-control' in request.path %}
            style="background-color: green;color: white;"
          {% endif %}
          href="{% url 'embarazos:create-control-embarazo' paciente.id %}">Agregar embarazo actual</a>
      <a class="btn btn-default"
          {% if 'crear-control' or 'agregar-ecografia' in request.path %}
            style="background-color: green;color: white;"
          {% endif %}
          href="{% url 'controles:list' paciente.id %}">Atenciones</a>
    </div>
  </div>
</div>

apps/embarazos/templates/embarazos/partials/ecografia_delete_js.html
{% load static %}

{% include 'session_security/all.html' %}
<script type="text/javascript">
  $('#eliminar-ecografia').click(function() {
    swal({
      title: "¿Está seguro de eliminar la ecografía?",
      text: "Una vez eliminada no será posible deshacer la acción realizada.",
      type: "warning",
      showCancelButton: true,
      confirmButtonColor: "#DD6B55",
      confirmButtonText: "Si, eliminar ecografía",
      cancelButtonText: "Cancelar",
      closeOnConfirm: false},
      function(){
        window.location = $('.btn-danger').attr('href');
        swal("Borrado", "La ecografía ha sido eliminada correctamente", "success");
      }
  );
  return false;
  });
</script>

apps/embarazos/templates/embarazos/partials/embarazo_delete_js.html
{% load static %}

{% include 'session_security/all.html' %}
<script type="text/javascript">
  $('#eliminar-embarazo-previo').click(function() {
    swal({
      title: "¿Está seguro de eliminar el embarazo?",
      text: "Una vez eliminado no será posible deshacer la acción realizada.",
      type: "warning",
      showCancelButton: true,
      confirmButtonColor: "#DD6B55",
      confirmButtonText: "Si, eliminar el embarazo",
      cancelButtonText: "Cancelar",
      closeOnConfirm: false},
      function(){
        window.location = $('.btn-danger').attr('href');
        swal("Borrado", "El embarazo ha sido eliminado correctamente", "success");
      }
  );
  return false;
  });
</script>

apps/embarazos/templates/embarazos/partials/input_inside_table.html
{% load static %}
{% load form_filter %}

<div class="form-group">
    <div class="col-sm-12">
        {% if addon %}
        <div class="input-group" style="width: 150px">
            {{ field|add_class:'form-control input-sm' }}
            <span class="input-group-addon">{{ addon }}</span>
        </div>
        {% else %}
        {{ field|add_class:'form-control input-sm' }}
        {% endif %}
        {% for error in field.errors %}
        <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
    </div>
</div>

apps/embarazos/templates/embarazos/partials/input_without_label.html
{% load static %}
{% load form_filter %}

{% include 'session_security/all.html' %}
<div class="form-group">
    <div class="col-sm-12">
        {{ field }}
        {% for error in field.errors %}
        <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
    </div>
</div>

apps/embarazos/templates/embarazos/partials/paciente_resume_header.html
{% load thumbnail %}
{% load static %}
{% load paciente_tags %}
{% url 'paciente:update' paciente.id as paciente_upd_url %}
{% url 'embarazos:create' paciente.id as create_emb_url %}
<div class="panel-body">
  <div class="row">
    <div class="col-md-2">
      {% if paciente.foto.name %}
        <img src="{% thumbnail paciente.foto 112x122 %}" width="112" height="112" alt="{{ paciente.nombre_completo }}" />
      {% else %}
        <img src="{% static 'img/avatar2.png' %}" width="112" height="112" alt="default foto" />
      {% endif %}
    </div>
    <div class="col-md-10">
      <h2>
        <a style="color: gray" href="{% url 'paciente:update' paciente.id %}">{{ paciente.nombre_completo.upper }}</a>
      </h2>
      <div class="row">
        <div class="col-sm-2">
          <p>N° HC: {{ paciente|hc:request }}</p>
          {% ifequal paciente.tipo_documento paciente.DOCUMENTO_DNI_RESPONSABLE %}
            <p>DNI Responsable {{ paciente.numero_documento }}</p>
          {% else %}
            <p>{{ paciente.nombre_documento }}: {{ paciente.numero_documento }}</p>
          {% endifequal %}
        </div>
        <div class="col-sm-2">
          <p>Edad: {{ paciente.edad }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="panel-body">
  <div class="col-sm-7 col-sm-offset-3">
    <div class="btn-group">
      <a class="btn btn-default" href="{% url 'partos:paciente_update' paciente.id %}">Afiliación</a>
      {% if 'pacientes.change_antecedenteginecologico' in user.get_all_permissions %}
        <a class="btn btn-default"
            {% if 'antecedente' in request.path %}
              style="background-color: green;color: white;"
            {% endif %}
            href="{% url 'partos:paciente_antecedentes_edit' paciente.id %}">Antecedentes</a>
      {% else %}
        <a class="btn btn-default"
            {% if 'antecedente' in request.path %}
              style="background-color: green;color: white;"
            {% endif %}
            href="{% url 'partos:paciente_antecedentes' paciente.id %}">Antecedentes</a>
      {% endif %}
      {% if 'embarazos.add_embarazo' in user.get_all_permissions %}
        <a class="btn btn-default"
            {% if 'registrar-embarazo' in request.path or 'editar-embarazo' in request.path %}
              style="background-color: green;color: white;"
            {% endif %}
            href="{% url 'partos:embarazo_create' paciente.id %}">Embarazo actual</a>

        <a class="btn btn-default"
            {% if 'registrar-ingreso' in request.path or 'ingreso_edit' in request.path %}

              style="background-color: green;color: white;"
            {% endif %}
            href="{% url 'partos:ingreso_register' paciente.id %}">Ingreso</a>
      {% endif %}
    </div>
  </div>
</div>

apps/embarazos/templates/embarazos/partials/paciente_resume_header_embarazo_previo.html
{% load thumbnail %}
{% load static %}
{% load paciente_tags %}
{% url 'partos:embarazo_create' paciente.id as create_emb_url %}
<div class="panel-body">
    <div class="row">
        <div class="col-md-2">
            {% if paciente.foto.name %}
            <img src="{% thumbnail paciente.foto 112x122 %}" width="112" height="112" alt="{{ paciente.nombre_completo }}"/>
            {% else %}
            <img src="{% static 'img/avatar2.png' %}" width="112" height="112" alt="default foto"/>
            {% endif %}
        </div>
        <div class="col-md-10">
            <h2>
                <a style="color: gray" href="{% url 'paciente:update' paciente.id %}">{{ paciente.nombre_completo.upper }}</a>
            </h2>
            <div class="row">
                <div class="col-sm-2">
                    <p>N° HC: {{ paciente|hc:request }}</p>
                    {% ifequal paciente.tipo_documento paciente.DOCUMENTO_DNI_RESPONSABLE %}
                    <p>DNI Responsable {{ paciente.numero_documento }}</p>
                    {% else %}
                        <p>{{ paciente.nombre_documento }}: {{ paciente.numero_documento }}</p>
                    {% endifequal %}
                </div>
                <div class="col-sm-2">
                    <p>Edad: {{ paciente.edad }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

apps/embarazos/templates/embarazos/partials/radio_select_true_false_none.html
{% load static %}

{% include 'session_security/all.html' %}
<div class="form-group">
    <label for="{{ field.auto_id }}" class="col-sm-6 control-label">{{ field.label }}</label>
    <div class="col-sm-6">
        <ul class="list-inline">
            <li>
                <label>
                    <input type="radio" name="{{ field.name }}" {% ifequal field_instance True %}checked{% endifequal %} value="True"/>
                    Si
                </label>
            </li>
            <li>
                <label>
                    <input type="radio" name="{{ field.name }}" {% ifequal field_instance False %}checked{% endifequal %} value="False"/>
                    No
                </label>
            </li>
            <li>
                <label>
                    <input type="radio" name="{{ field.name }}" {% ifequal field_instance None %}checked{% endifequal %} value="None"/>
                    N/A
                </label>
            </li>
        </ul>
        {% for error in field.errors %}
        <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
    </div>
</div>

apps/embarazos/templates/embarazos/partials/ultimos_embarazos_table.html
{% load static %}

<div class="panel-body">
    <div class="panel panel-default" id="data-buscar-body">
        <div id="data-head" class="panel-heading">
            Embarazos previos
            {% url 'paciente:antecedentes_edit' paciente.id as antecedentes_url %}
            {% if 'embarazos.add_ultimoembarazo' in user.get_all_permissions %}
            <div class="pull-right">
                 <a class="btn btn-green" href="{% url 'embarazos:ultimo_embarazo_create' paciente.id %}">
                    <span class="glyphicon glyphicon-plus"></span> Agregar datos de embarazo previo
                </a>
            </div>
            {% endif %}
        </div>

        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Gestación</th>
                <th>Fecha</th>
                <th>Tipo gestación</th>
                <th>Terminacion</th>
                <th>Aborto</th>
                <th>Vive</th>
                <th>Muerte</th>
                <th>Peso</th>
                <th>Sexo</th>
                <th>EG</th>
                <th>Lugar</th>
                <th>Lactancia</th>
                <th>Observación</th>
                {% if 'embarazos.change_ultimoembarazo' in user.get_all_permissions %}
                <th>Opciones</th>
                <th>Eliminar</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for embarazo in embarazos %}
                {% for bebe in embarazo.bebes_ordered %}
                <tr>
                    <td>{{ embarazo.numero }}</td>
                    <td>{{ bebe.fecha|date:'d/m/Y' }}</td>
                    <td>{{ embarazo.print_tipo }}</td>
                    <td>{{ bebe.print_terminacion }}</td>
                    <td>{{ bebe.print_aborto }}</td>
                    <td>{% if bebe.vive %}Si{% else %}No{% endif %}</td>
                    <td>{{ bebe.print_muerte }}</td>
                    <td>{% if bebe.peso %}{{ bebe.peso }} g{% endif %}</td>
                    <td>{{ bebe.print_sexo|slice:':1' }}</td>
                    <td>{{ bebe.edad_gestacional }}</td>
                    <td>{{ bebe.print_lugar }}</td>
                    <td>{{ bebe.print_lactancia }}</td>
                    <td>{{ bebe.observacion }}</td>
                    {% if 'embarazos.change_ultimoembarazo' in user.get_all_permissions %}
                    <td>
                        <a class="btn btn-default" href="{% url 'embarazos:ultimo_embarazo_edit' paciente.id embarazo.id %}">Editar</a>
                    </td>
                    <td>
                        <div id="eliminar-embarazo-previo">
                          <a class="btn btn-danger" href="{% url 'embarazos:ultimo_embarazo_delete' paciente.id embarazo.id %}">Eliminar</a>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% include 'embarazos/partials/embarazo_delete_js.html' %}