apps/puerperio/urls.py
from django.conf.urls import patterns, url, include

import views

reports = patterns(
    '',
    url(r'^epicrisis/(?P<egreso_gestante_id>\d+)/$',
        views.EpicrisisReportView.as_view(), name='epicrisis')
)

urlpatterns = patterns(
    '',
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^paciente/buscar/$',
        views.PPacienteSearchView.as_view(), name='paciente_search'),
    url(r'^resumen/(?P<terminacion_embarazo_id>\d+)/$',
        views.ResumeView.as_view(), name='resume'),
    url(r'^reportes/', include(reports, namespace='reports')),
    url(r'^(?P<terminacion_embarazo_id>\d+)/monitoreo/$',
        views.MonitoreoView.as_view(), name='monitoreo'),
    url(r'^(?P<terminacion_embarazo_id>\d+)/monitoreo/medicion/(?P<medicion_id>\d+)/$',
        views.MonitoreoMedicionUpdateView.as_view(
        ), name='monitoreo_medicion'),
    url(r'^terminacion_embarazo/(?P<terminacion_embarazo_id>\d+)/egreso/redirect/$',
        views.EgresoGestanteView.as_view(), name='egreso_gestante'),
    url(r'^terminacion_embarazo/(?P<terminacion_embarazo_id>\d+)/registrar-egreso/$',
        views.EgresoGestanteCreateView.as_view(
        ), name='egreso_gestante_create'),
    url(r'^terminacion_embarazo/(?P<terminacion_embarazo_id>\d+)/egreso/$',
        views.EgresoGestanteUpdateView.as_view(), name='egreso_gestante_edit'),
    url(r'^(?P<terminacion_embarazo_id>\d+)/recien-nacido/create/$',
        views.RecienNacidoCreateView.as_view(), name='recien_nacido_create'),
    url(r'^(?P<terminacion_embarazo_id>\d+)/recien-nacido/(?P<recien_nacido_id>\d+)/edit/',
        views.RecienNacidoUpdateView.as_view(), name='recien_nacido_edit'),
    url(r'^(?P<terminacion_embarazo_id>\d+)/cierre-puerpera/$',
        views.TerminacionPuerperaView.as_view(), name='cierre_puerpera'),
)

wawared/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

handler403 = 'perfiles.views.handler_403'

admin.autodiscover()

urlpatterns = patterns(
    '',
    # Api
    url(r'^api/', include('api.urls', namespace='api')),
    # CIE
    url(r'^cie/', include('cie.urls', namespace='cie')),
    # CPT
    url(r'^cpt/', include('cpt.urls', namespace='cpt')),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Perfiles
    url(r'^', include('perfiles.urls')),
    # Dahboard
    url(r'^', include('dashboard.urls')),
    # Ubigeo
    url('^ubigeo/', include('ubigeo.urls', namespace='ubigeo')),
    # Gestantes
    url(r'^hce/', include('gestantes.urls', namespace='gestantes')),
    url(r'session_security/', include('session_security.urls')),
    # Dnireniec
    url(r'^dnireniec/', include('dnireniec.urls', namespace='dnireniec')),
    # Partos
    url(r'^partos/', include('partos.urls', namespace='partos')),
    # Firma
    url(r'^firma/', include('firma.urls', namespace='firma')),
    # Puerperio
    url(r'^puerperio/', include('puerperio.urls', namespace='puerperio')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/puerperio/models.py
# coding: utf-8

from __future__ import unicode_literals

from django.core.validators import MinValueValidator
from django.core.validators import MaxValueValidator
from django.db import models
from django.conf import settings


class RecienNacido(models.Model):

    SEXO_MASCULINO = 'm'
    SEXO_FEMENINO = 'f'
    SEXO_INDETERMINADO = 'indeterminado'

    SEXO_CHOICES = (
        (SEXO_MASCULINO, u'Masculino'),
        (SEXO_FEMENINO, u'Femenino'),
        (SEXO_INDETERMINADO, 'Indeterminado')
    )

    PESO_EG_ADECUADO = 'adecuado'
    PESO_EG_PEQUENO = 'pequeño'
    PESO_EG_GRANDE = 'grande'

    PESO_EG_CHOICES = (
        (PESO_EG_ADECUADO, 'Adecuado'),
        (PESO_EG_PEQUENO, 'Pequeño'),
        (PESO_EG_GRANDE, 'Grande')
    )

    EXAMEN_FISICO_NORMAL = 'normal'
    EXAMEN_FISICO_ANORMAL = 'anormal'

    EXAMEN_FISICO_CHOICES = (
        (EXAMEN_FISICO_NORMAL, 'Normal'),
        (EXAMEN_FISICO_ANORMAL, 'Anormal')
    )

    terminacion_embarazo = models.ForeignKey(
        'partos.TerminacionEmbarazo', related_name='recien_nacidos')
    nombres = models.CharField(u'Nombres', max_length=100, null=True)
    apellido_paterno = models.CharField(
        u'Apellido Paterno', max_length=50, null=True)
    apellido_materno = models.CharField(
        u'Apellido Materno', max_length=50, null=True)
    sexo = models.CharField('Sexo', max_length=2, choices=SEXO_CHOICES)
    peso = models.SmallIntegerField('Peso', validators=[
        MinValueValidator(100), MaxValueValidator(9999)
    ])
    vive = models.BooleanField('¿Vive?', default=True)
    temperatura = models.FloatField('Temperatura', validators=[
        MinValueValidator(25), MaxValueValidator(50)
    ])
    perimetro_cefalico = models.IntegerField(
        'Perímetro cefálico', null=True, blank=True)
    perimetro_toraxico = models.IntegerField(
        'Perímetro toráxico', null=True, blank=True)
    talla = models.FloatField('Talla')
    edad_por_examen_fisico = models.SmallIntegerField('Edad por examen físico', blank=True, null=True, validators=[
        MinValueValidator(10), MaxValueValidator(99)
    ])
    peso_por_edad_gestacional = models.CharField(
        'Peso por edad gestacional', max_length=20, choices=PESO_EG_CHOICES, default=PESO_EG_ADECUADO)
    apgar_1 = models.SmallIntegerField('APGAR 1\'', blank=True, null=True, validators=[
        MinValueValidator(0), MaxValueValidator(10)
    ])
    apgar_5 = models.SmallIntegerField('APGAR 5\'', blank=True, null=True, validators=[
        MinValueValidator(0), MaxValueValidator(10)
    ])
    examen_fisico = models.CharField(
        'Examen Físico', max_length=10, choices=EXAMEN_FISICO_CHOICES, default=EXAMEN_FISICO_NORMAL)
    necropsia = models.NullBooleanField('Necropsia', default=None)
    hospitalizacion = models.BooleanField('Hospitalización', default=False)

    tiene_egreso = models.BooleanField(default=False)

    # can: condicion al nacer
    can_llanto_inmediato = models.BooleanField(
        'Llanto inmediato', default=False)
    can_cianotico = models.BooleanField('Cianótico', default=False)
    can_palido = models.BooleanField('Pálido', default=False)
    can_pletorico = models.BooleanField('Pletórico', default=False)
    can_flacido = models.BooleanField('Flácido', default=False)
    can_circular = models.BooleanField('Circular', default=False)
    can_asfixia = models.BooleanField('Asfixia al nacer', default=False)
    can_asfixia_severa = models.BooleanField('Asfixia severa', default=False)
    can_impregnacion_meconial = models.BooleanField(
        'Impregnación. Meconial', default=False)
    can_caput = models.BooleanField('Caput', default=False)
    can_cefalohematoma = models.BooleanField('Cefalohematoma', default=False)
    can_edematoso = models.BooleanField('Edematoso', default=False)
    can_ictericia = models.BooleanField('Ictericia', default=False)

    tiene_malformaciones_congenitas = models.BooleanField(
        '¿Tiene malformaciones congénitas?', default=False)

    # mc: malformaciones congenitas
    mc_sindrome_de_down = models.BooleanField(
        'Síndrome de Down', default=False)
    mc_siames = models.BooleanField('Siames', default=False)
    mc_labio_leporino = models.BooleanField('Labio Leporino', default=False)
    mc_paladar_rendido = models.BooleanField('Paladar rendido', default=False)
    mc_polidactilia = models.BooleanField('Polidactilia', default=False)

    # ai: atención inmediata
    ai_aspiracion_oro_nasal = models.BooleanField(
        'Aspiración oro nasal', default=False)
    ai_aspiracion_endotraqueal = models.BooleanField(
        'Aspiración endotraqueal', default=False)
    ai_ventilacion_asistida = models.BooleanField(
        'Ventilación asistida', default=False)
    ai_oxigeno = models.BooleanField('Oxigeno', default=False)
    ai_masaje_cardiaco = models.BooleanField('Masaje cardiaco', default=False)
    ai_bicarbonato = models.BooleanField('Bicarbonato', default=False)
    ai_adrenalina = models.BooleanField('Adrenalina', default=False)

    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='recien_nacidos_c')
    modifier = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='recien_nacidos_m')

    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)

    @property
    def nombre_completo(self):
        return '{} {} {}'.format(self.nombres, self.apellido_paterno, self.apellido_materno)


class Monitoreo(models.Model):

    ABIERTO = 'abierto'
    CERRADO = 'cerrado'

    establecimiento = models.ForeignKey('establecimientos.Establecimiento', null=True, related_name='monitoreos')
    paciente = models.ForeignKey('pacientes.Paciente', related_name='monitoreos')
    embarazo = models.OneToOneField('embarazos.Embarazo', related_name='monitoreos')
    terminacion_embarazo = models.OneToOneField('partos.TerminacionEmbarazo', related_name='monitoreo_puerperio')

    status = models.CharField(max_length=20, default=ABIERTO)

    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='monitoreo_c')
    modifier = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='monitoreo_m')

    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)


class MonitoreoMedicion(models.Model):

    FORMADO = 'formado'
    UMBILICADO = 'umbilicado'
    PLANO = 'plano'
    BLANDAS = 'blandas'
    TURGENTES = 'turgentes'
    SECRETANTES = 'secretantes'
    CONTRAIDO = 'contraido'
    NO_CONTRAIDO = 'no contraido'
    HEMATICOS = 'hematicos'
    SERO_HEMATICOS = 'serohematicos'
    SEROSOS = 'serosos'
    MAL_OLOR = 'mal olor'
    SIN_OLOR = 'sin olor'
    MEDIO_LATERAL_IZQUIERDA = 'medio lateral izquierda'
    MEDIO_LATERAL_DERECHA = 'medio lateral derecha'
    CON_EDEMA = 'con edema'
    DEHISENCIA_HERIDA = 'dehisencia de herida'
    BORDES_AFRONTADOS = 'bordes afrontados'
    BORDES_NO_AFRONTADOS = 'bordes no afrontados'
    DOLOROSO = 'doloroso'
    NO_SE_HIZO = 'no se hizo'
    NO_APLICA = 'no aplica'
    REACTIVO = 'reactivo'
    NO_REACTIVO = 'no reactivo'

    NO_NO_CHOICES = (
        (NO_SE_HIZO, 'No se hizo'),
        (NO_APLICA, 'No aplica')
    )

    MAMAS_PEZON_CHOICES = (
        (FORMADO, 'Formado'),
        (UMBILICADO, 'Umbilicado'),
        (PLANO, 'Plano')
    )

    MAMAS_CARACTERISTICAS_CHOICES = (
        (BLANDAS, 'Blandas'),
        (TURGENTES, 'Turgentes'),
        (SECRETANTES, 'Secretantes')
    )

    UTERO_CARACTERISTICAS_CHOICES = (
        (CONTRAIDO, 'Contraido'),
        (NO_CONTRAIDO, 'No contraido')

    )

    UTERO_UBICACION_CHOICES = (
        ('3cm encima', 'A 3cm por encima'),
        ('2cm encima', 'A 2cm por encima'),
        ('1cm encima', 'A 1cm por encima'),
        ('nivel cicatriz', 'A nivel de la cicatriz'),
        ('1cm debajo', 'A 1cm por debajo'),
        ('2cm debajo', 'A 2cm por debajo'),
        ('3cm debajo', 'A 3cm por debajo')
    )

    LOQUIOS_CARACTERISTICAS_CHOICES = (
        (HEMATICOS, 'Hematicos'),
        (SERO_HEMATICOS, 'Sero-hematicos'),
        (SEROSOS, 'Serosos')
    )

    LOQUIOS_CANTIDAD_CHOISES = (
        ('+', '+'),
        ('++', '++'),
        ('+++', '+++')
    )

    LOQUIOS_OLOR_CHOISES = (
        (MAL_OLOR, 'Mal olor'),
        (SIN_OLOR, 'Sin olor')
    )

    EPISEOTOMIA_TIPO_CHOISES = (
        (MEDIO_LATERAL_DERECHA, 'Medio lateral derecha'),
        (MEDIO_LATERAL_IZQUIERDA, 'Medio lateral izquierda'),
        (CON_EDEMA, 'Con edema'),
        (DEHISENCIA_HERIDA, 'Dehisencia de herida')
    )

    PURULENTO = 'purulento'
    INFECTADA = 'infectada'
    FLOGOSIS = 'flogosis'
    SIN_DOLOR = 'sin dolor'

    EPISEOTOMIA_CARACTERISTICAS_CHOISES = (
        (BORDES_AFRONTADOS, 'Bordes afrontados'),
        (BORDES_NO_AFRONTADOS, 'Bordes no afrontados'),
        (DOLOROSO, 'Doloroso'),
        (PURULENTO, 'Purulento'),
        (INFECTADA, 'Infectada'),
        (FLOGOSIS, 'Flogosis'),
        (SIN_DOLOR, 'Sin dolor')
    )

    VP_CL = 'cl na'
    VP_DEXTROZA = 'dextroza'
    VP_HEMACELL = 'hemacell'

    VP_CHOICES = (
        (VP_CL, 'Cl Na'),
        (VP_DEXTROZA, 'Dextroza'),
        (VP_HEMACELL, 'Hemacell')
    )

    REACTIVO_NO_REACTIVO_CHOICES = (
        (REACTIVO, 'Reactivo'),
        (NO_REACTIVO, 'No reactivo')
    ) + NO_NO_CHOICES

    fecha = models.DateField('Fecha')
    hora = models.TimeField('Hora')

    monitoreo = models.ForeignKey('Monitoreo', related_name='mediciones')
    establecimiento = models.ForeignKey(
        'establecimientos.Establecimiento', related_name='mediciones')

    # Funciones vitales
    presion_sistolica = models.SmallIntegerField('Presion sistolica', null=True, blank=True, validators=[
        MinValueValidator(0), MaxValueValidator(300)
    ])
    presion_diastolica = models.SmallIntegerField('Presion diastolica', null=True, blank=True, validators=[
        MinValueValidator(0), MaxValueValidator(200)

apps/puerperio/templates/puerperio/egreso_gestante.html
{% extends 'dashboard/base_puerperio.html' %}
{% load static %}
{% load form_tags %}
{% block title %}Egreso de la gestante{% endblock %}
{% block extra_style %}
    <link rel="stylesheet" href="{% static 'css/datepicker.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-timepicker.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/select2.css' %}" />
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div id="data-buscar">
            <div class="panel panel-default">
                <div id="data-head" class="panel-heading">
                    <h3 class="panel-title">Registro de recien nacidos</h3>
                </div>
                {% include 'partos/paciente_header.html' with paciente=terminacion_embarazo.paciente %}
                {% include 'puerperio/tabs.html' with terminacion_embarazo=terminacion_embarazo %}
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div id="data-buscar">
            <div class="panel panel-default">
                <div id="data-head" class="panel-heading">
                    <h3 class="panel-title">Egreso de la paciente</h3>
                </div>
                <div id="data-gestante" class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" method="post">
                            <div class="row">
                                {% csrf_token%}
                                <div class="col-md-6">
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            {% include 'dashboard/partials/form_group_date.html' with field=form.fecha %}
                                            {% include 'dashboard/partials/form_group_input.html' with field=form.hora %}
                                            {% include 'dashboard/partials/form_group_input.html' with field=form.tipo %}
                                            {% include 'dashboard/partials/form_group_input.html' with field=form.diagnostico %}
                                            {% include 'dashboard/partials/form_group_input.html' with field=form.diagnostico_traslado %}
                                            {% include 'dashboard/partials/form_group_input.html' with field=form.diagnostico_fallecimiento %}
                                            <div class="form-group">
                                                <label for="{{ form.cui.auto_id }}" class="col-md-5 control-label">{{ form.cui.label }}</label>
                                                <div class="col-md-7">
                                                    <ul class="list-inline">
                                                        <li>
                                                            <label>
                                                                <input type="radio" name="{{ form.cui.html_name }}" {% ifequal form.instance.cui True %}checked{% endifequal %} value="True"
                                                                /> Si
                                                            </label>
                                                        </li>
                                                        <li>
                                                            <label>
                                                                <input type="radio" name="{{ form.cui.html_name }}" {% ifequal form.instance.cui False %}checked{% endifequal %} value="False"
                                                                /> No
                                                            </label>
                                                        </li>
                                                    </ul>
                                                    {% for error in form.cui.errors %}
                                                    <div class="alert alert-danger">{{ error }}</div>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="{{ form.seguro.auto_id }}" class="col-md-5 control-label">{{ form.seguro.label }}</label>
                                                <div class="col-md-7">
                                                    <ul class="list-inline">
                                                        <li>
                                                            <label>
                                                                <input type="radio" name="{{ form.seguro.html_name }}" {% ifequal form.instance.seguro True %}checked{% endifequal %} value="True"
                                                                /> Si
                                                            </label>
                                                        </li>
                                                        <li>
                                                            <label>
                                                                <input type="radio" name="{{ form.seguro.html_name }}" {% ifequal form.instance.seguro False %}checked{% endifequal %} value="False"
                                                                /> No
                                                            </label>
                                                        </li>
                                                    </ul>
                                                    {% for error in form.seguro.errors %}
                                                    <div class="alert alert-danger">{{ error }}</div>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            Anticonceptivos
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_ligadura_tubaria %}
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_anticoncec_combinada %}
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_abstinencia_periodica %}
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_mela %}
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_solo_ori_consej %}
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_condon %}
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_inyectables %}
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_ninguno %}
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_diu %}
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_orales %}
                                            {% include 'dashboard/partials/checkbox.html' with field=form.ant_otro %}
                                            {% include 'dashboard/partials/form_group_textarea.html' with field=form.ant_observaciones %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <input class="btn btn-green" style="float: right;" type="submit" value="Guardar" />
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}
{% block bottom_scripts %}
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/bootstrap-timepicker.min.js' %}"></script>
<script src="{% static 'js/vendor/select2.min.js' %}"></script>
{% cie_select form.diagnostico %}
{% cie_select form.diagnostico_traslado %}
{% cie_select form.diagnostico_fallecimiento %}
<script>
    $(document).ready(function () {
        $('#id_fecha').datepicker();
        $('#id_hora').timepicker({
            defaultTime: 'current',
            showSeconds: false,
            template: false,
            showMeridian: false
        });
        var $egresoTipo = $('#id_tipo');
        var $diagnosticoTrasladoWrapper = $('#id_diagnostico_traslado').parents('.form-group');
        var $diagnosticoFallecimientoWrapper = $('#id_diagnostico_fallecimiento').parents('.form-group');
        var $establecimientoTrasladoWrapper = $('#id_establecimiento_traslado').parents('.form-group');
        changeTipo($egresoTipo.val());
        $egresoTipo.on('change', function () {
            changeTipo(this.value);
        });
        function changeTipo(tipo) {
            if (tipo === 'traslado') {
                $diagnosticoFallecimientoWrapper.hide();
                $diagnosticoTrasladoWrapper.show();
                $establecimientoTrasladoWrapper.show();
            } else if (tipo === 'fallece') {
                $diagnosticoFallecimientoWrapper.show();
                $diagnosticoTrasladoWrapper.hide();
                $establecimientoTrasladoWrapper.hide();
            } else {
                $diagnosticoFallecimientoWrapper.hide();
                $diagnosticoTrasladoWrapper.hide();
                $establecimientoTrasladoWrapper.hide();
            }
        }
    });
</script> {% endblock %}

apps/puerperio/templates/puerperio/recien_nacido_form_js.html
{% load static %}
{% load form_tags %}
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/bootstrap-timepicker.min.js' %}"></script>
<script src="{% static 'js/vendor/select2.min.js' %}"></script>
    {% cie_select egreso_form.diagnostico %}
    {% cie_select egreso_form.diagnostico_traslado %}
    {% cie_select egreso_form.diagnostico_fallecimiento %}
    <script>
        $(document).on('ready', function () {
            $('#id_egreso-fecha').datepicker();
            $('#id_egreso-hora').timepicker({
                defaultTime: 'current',
                showSeconds: false,
                template: false,
                showMeridian: false
            });
            var $egresoTipo = $('#id_egreso-tipo');
            var $vive = $('#id_vive');
            var $diagnosticoTrasladoWrapper = $('#id_egreso-diagnostico_traslado').parents('.form-group');
            var $diagnosticoFallecimientoWrapper = $('#id_egreso-diagnostico_fallecimiento').parents('.form-group');
            var $necropsiaWrapper = $('input[name="necropsia"]').parents('.form-group');
            var $establecimientoTrasladoWrapper = $('#id_egreso-establecimiento_traslado').parents('.form-group');

            var $tieneEgreso = $('#id_tiene_egreso');
            var $tieneMalformacionesCongenitas = $('#id_tiene_malformaciones_congenitas');
            var $egresoFields = $('#egreso-fields');
            var $malformacionesCongenitasFields = $('#malformaciones-congenitas');

            changeTipo($egresoTipo.val());
            checkEgreso($tieneEgreso.is(':checked'));
            checkVive($vive.is(':checked'));
            checkMalformacionesCongenitas($tieneMalformacionesCongenitas.is(':checked'));
            $egresoTipo.on('change', function () {
                changeTipo(this.value);
            });

            $tieneEgreso.on('change', function () {
                checkEgreso($(this).is(':checked'));
            });

            $vive.on('change', function () {
                checkVive($(this).is(':checked'));
            });

            $tieneMalformacionesCongenitas.on('change', function () {
                checkMalformacionesCongenitas($(this).is(':checked'));
            });

            function changeTipo(tipo) {
                if (tipo === 'traslado') {
                    $diagnosticoFallecimientoWrapper.hide();
                    $diagnosticoTrasladoWrapper.show();
                    $establecimientoTrasladoWrapper.show();
                } else if (tipo === 'fallece') {
                    $diagnosticoFallecimientoWrapper.show();
                    $diagnosticoTrasladoWrapper.hide();
                    $establecimientoTrasladoWrapper.hide();
                } else {
                    $diagnosticoFallecimientoWrapper.hide();
                    $diagnosticoTrasladoWrapper.hide();
                    $establecimientoTrasladoWrapper.hide();
                }
            }
            function checkEgreso(value) {
                if (value) {
                    $egresoFields.show();
                } else {
                    $egresoFields.hide();
                }
            }
            function checkVive(value) {
                if (value) {
                    $necropsiaWrapper.hide();
                } else {
                    $necropsiaWrapper.show();
                }
            }
            function checkMalformacionesCongenitas(value) {
                if (value) {
                    $malformacionesCongenitasFields.show();
                } else {
                    $malformacionesCongenitasFields.hide();
                }
            }
        });
</script>

apps/puerperio/templates/puerperio/tabs.html
{% if terminacion_embarazo.id %}
<div class="panel-body">
    <div class="col-sm-10 col-sm-offset-2">
        <div class="btn-group">
            <a href="{% url 'puerperio:monitoreo' terminacion_embarazo.id %}"
            {% if 'monitoreo' in request.path %}
                style="background-color: green;color: white;"
            {% endif %}
            class="btn btn-default" type="button" >Monitoreo</a>
            <a href="{% url 'puerperio:egreso_gestante' terminacion_embarazo.id %}"
            {% if 'egreso' in request.path %}
                style="background-color: green;color: white;"
            {% endif %}
            class="btn btn-default" type="button" >Egreso de la paciente</a>
            <a href="{% url 'puerperio:resume' terminacion_embarazo.id %}"
            {% if 'resumen' in request.path %}
                style="background-color: green;color: white;"
            {% endif %}
            class="btn btn-default" type="button" >Egreso de recién nacidos</a>
            <a href="{% url 'puerperio:cierre_puerpera' terminacion_embarazo.id %}"
            {% if 'cierre' in request.path %}
                style="background-color: green;color: white;"
            {% endif %}
            class="btn btn-default" type="button" >Cierre puerpera</a>
        </div>
    </div>
</div>
{% endif %}
<div class="modal fade" id="reports-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Reportes puerperio</h4>
            </div>
            <div class="modal-body">
                <div class="list-group">
                {% if terminacion_embarazo.egreso_gestante %}
                    <a class="list-group-item" href="{% url 'puerperio:reports:epicrisis' terminacion_embarazo.egreso_gestante.id %}">Epicrisis</a>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>