apps/cie/urls.py
from django.conf.urls import patterns, url
from .views import cie_search

urlpatterns = patterns(
    '',
    url(r'^buscar-cie/$', cie_search, name='api_search'),
)

apps/controles/urls.py
from django.conf.urls import patterns, url, include

import views

reports = patterns(
    '',
    url(
        r'^solicitud-examenes-clinicos/(?P<control_id>\d+)/$',
        views.SolicitudExamenesClinicosReportView.as_view(),
        name='solicitud_examenes_clinicos'),
    url(
        r'historia-clinica/(?P<control_id>\d+)/$',
        views.HistoriaClinicaReportView.as_view(),
        name='historia_clinica'),
    url(
        r'historia-clinica/(?P<control_id>\d+)/(?P<accion_id>\d+)/$',
        views.HistoriaClinicaReportView.as_view(),
        name='historia_clinica'),
    url(
        r'plan-parto/(?P<control_id>\d+)/$',
        views.PlanPartoReportView.as_view(),
        name='plan_parto'),
    url(
        r'plan-parto/(?P<control_id>\d+)/(?P<accion_id>\d+)/$',
        views.PlanPartoReportView.as_view(),
        name='plan_parto'),
    url(
        r'tarjeta-seguimiento/(?P<control_id>\d+)/$',
        views.TarjetaSeguimientoReportView.as_view(),
        name='tarjeta_seguimiento'),
    url(
        r'receta-unica-estandarizada/(?P<control_id>\d+)/$',
        views.RecetaUnicaEstandarizadaReportView.as_view(),
        name='receta_unica_estandarizada'),
    url(
        r'receta-unica-flujo-vaginal/(?P<control_id>\d+)/$',
        views.RecetaUnicaFlujoVaginalReportView.as_view(),
        name='receta_unica_flujo_vaginal'),
    url(
        r'receta-unica-prueba-rapida/(?P<control_id>\d+)/$',
        views.RecetaUnicaPruebaRapidaReportView.as_view(),
        name='receta_unica_prueba_rapida'),
    url(
        r'formato-unico-atencion/(?P<control_id>\d+)/$',
        views.FormatoUnicoAtencionReportView.as_view(),
        name='formato_unico_atencion'),
    url(
        r'hoja-referencia/(?P<control_id>\d+)/$',
        views.HojaReferenciaReportView.as_view(),
        name='hoja_referencia'),
    url(
        r'carne-control-prenatal/(?P<control_id>\d+)/$',
        views.CarneControlPrenatalReportView.as_view(),
        name='carne_control_prenatal'),
    url(
        r'^solicitud-examen-citologico/(?P<control_id>\d+)/$',
        views.SolicitudExamenCitologicoReportView.as_view(),
        name='solicitud_examen_citologico'),
    url(
        r'^solicitud-prueba-elisa/(?P<control_id>\d+)/$',
        views.SolicitudPruebaElisaReportView.as_view(),
        name='solicitud_prueba_elisa'),
    url(
        r'^control-prenatal-excel/(?P<control_id>\d+)/$',
        views.ControlPrenatalExcelReportView.as_view(),
        name='control_prenatal_excel'),
    url(
        r'^control-prenatal-excel/(?P<control_id>\d+)/(?P<accion_id>\d+)/$',
        views.ControlPrenatalExcelReportView.as_view(),
        name='control_prenatal_excel')
)

fua = patterns(
    '',
    url(
        r'^009/(?P<control_id>\d+)/$',
        views.Fua009ExcelReportView.as_view(),
        name='009'),
    url(
        r'^011/(?P<control_id>\d+)/$',
        views.Fua011ExcelReportView.as_view(),
        name='011'),
    url(
        r'^013/(?P<control_id>\d+)/$',
        views.Fua013ExcelReportView.as_view(),
        name='013'),
    url(
        r'^024/(?P<control_id>\d+)/$',
        views.Fua024ExcelReportView.as_view(),
        name='024'),
    url(
        r'^071/(?P<control_id>\d+)/$',
        views.Fua071ExcelReportView.as_view(),
        name='071'),
)

urlpatterns = patterns(
    '',
    url(r'^reportes/', include(reports, namespace='reports')),
    url(r'^fua/', include(fua, namespace='fua')),
    url(
        r'^(?P<paciente_id>\d+)/controles/$',
        views.ControlesView.as_view(),
        name='list'),
    url(
        r'^control/(?P<id>\d+)/$',
        views.ControlDetailView.as_view(),
        name='detail'),
    url(
        r'^control/(?P<id>\d+)/editar/$',
        views.ControlUpdateView.as_view(),
        name='edit'),
    url(
        r'^control/(?P<id>\d+)/eiminar/$',
        views.ControlDeleteView.as_view(),
        name='delete'),
    url(
        r'^control/(?P<id>\d+)/sintomas/$',
        views.SintomasDetailView.as_view(),
        name='sintomas_detail'),
    url(
        r'^control/(?P<id>\d+)/sintomas/edit/$',
        views.SintomasView.as_view(),
        name='sintomas'),
    url(
        r'^control/(?P<id>\d+)/diagnostico/$',
        views.DiagnosticoDetailView.as_view(),
        name='diagnostico_detail'),
    url(
        r'^control/(?P<id>\d+)/diagnostico/editar/$',
        views.DiagnosticoView.as_view(),
        name='diagnostico'),
    url(
        r'^control/(?P<id>\d+)/examen-fisico/$',
        views.ExamenFisicoDetailView.as_view(),
        name='examen_fisico_detail'),
    url(
        r'^control/(?P<id>\d+)/examen-fisico/editar/$',
        views.ExamenFisicoView.as_view(),
        name='examen_fisico'),
    url(
        r'^control/(?P<id>\d+)/laboratorio/$',
        views.LaboratorioDetailView.as_view(),
        name='laboratorio_detail'),
    url(
        r'^control/(?P<id>\d+)/laboratorio/editar/$',
        views.LaboratorioView.as_view(),
        name='laboratorio'),
    url(
        r'^(?P<embarazo_id>\d+)/crear-control/$',
        views.ControlCreateView.as_view(),
        name='create'),
    url(
        r'^control/(?P<id>\d+)/data/crecimiento-neonatal/$',
        views.DataCrecimientoNeonatalView.as_view(),
        name='data_crecimiento_neonatal'),
    url(
        r'^control/(?P<id>\d+)/data/altura-uterina/$',
        views.DataAlturaUterinaView.as_view(),
        name='data_altura_uterina'),
    url(
        r'^control/(?P<id>\d+)/data/ganancia-peso-materno/$',
        views.DataGananciaPesoMaternoView.as_view(),
        name='data_ganancia_peso_materno'),
)

apps/dashboard/urls.py
from django.conf.urls import patterns, url, include

import views

urlpatterns = patterns(
    '',
    url(r'^$', views.DashboardHomeView.as_view(), name='dashboard_home'),
    url(r'^paciente/', include('pacientes.urls', namespace='paciente')),
    url(r'^paciente/', include('embarazos.urls', namespace='embarazos')),
    url(r'^paciente/', include('controles.urls', namespace='controles')),
    url(
        r'^reportes-estadisticos/',
        include('indicadores.urls', namespace='indicadores')),
    url(r'^citas/', include('citas.urls', namespace='cita')),
    url(
        r'^establecimientos/',
        include('establecimientos.urls', namespace='establecimientos')),
)

apps/embarazos/urls.py
from django.conf.urls import patterns, url, include

import views

reports = patterns(
    '',
    url(r'^ficha-tamizaje/(?P<embarazo_id>\d+)/$',
        views.FichaTamizajeReportView.as_view(),
        name='ficha_tamizaje'),
    url(r'^ficha-tamizaje/(?P<embarazo_id>\d+)/(?P<accion_id>\d+)/$',
        views.FichaTamizajeReportView.as_view(),
        name='ficha_tamizaje'),
    url(r'^tamizaje-depresion/(?P<embarazo_id>\d+)/$',
        views.TamizajeDepresionReportView.as_view(),
        name='tamizaje_depresion'),
)

urlpatterns = patterns(
    '',
    url(r'^reportes/',
        include(reports, namespace='reports')),
    url(r'^(?P<paciente_id>\d+)/embarazos-previos/$',
        views.UltimosEmbarazosView.as_view(),
        name='ultimos_embarazos'),
    url(r'^(?P<paciente_id>\d+)/ecografias/$',
        views.EcografiasView.as_view(),
        name='ecografias'),
    url(r'^(?P<paciente_id>\d+)/agregar-ecografia/$',
        views.EcografiaCreateView.as_view(),
        name='ecografia_create'),
    url(r'^(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/editar/$',
        views.EcografiaUpdateView.as_view(),
        name='ecografia_edit'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo-previo/$',
        views.UltimoEmbarazoCreateView.as_view(),
        name='ultimo_embarazo_create'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/$',
        views.UltimoEmbarazoUpdateView.as_view(),
        name='ultimo_embarazo_edit'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/eliminar/$',
        views.UltimoEmbarazoDeleteView.as_view(),
        name='ultimo_embarazo_delete'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo/$',
        views.EmbarazoCreateView.as_view(),
        name='create'),
    url(r'^(?P<paciente_id>\d+)/registrar-control-embarazo/$',
        views.EmbarazoControlCreateView.as_view(),
        name='create-control-embarazo'),
    url(r'^(?P<paciente_id>\d+)/editar-embarazo-actual/$',
        views.EmbarazoUpdateCurrentView.as_view(),
        name='update_current'),
    url(r'^plan-de-parto/(?P<embarazo_id>\d+)/$',
        views.PlanPartoView.as_view(),
        name='plan_parto'),
    url(r'^plan-de-parto/(?P<embarazo_id>\d+)/edit/$',
        views.PlanPartoUpdateView.as_view(),
        name='plan_parto_edit'),
    url(r'^(?P<paciente_id>\d+)/terminar-embarazo/(?P<embarazo_id>\d+)/$',
        views.TerminarEmbarazoView.as_view(),
        name='terminar_embarazo'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo-previo'
        r'/embarazo/(?P<embarazo_id>\d+)/$',
        views.UltimoEmbarazoFromEmbarazoCreateView.as_view(),
        name='ultimo_embarazo_from_embarazo_create'),
    url(r'^(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/eliminar/$',
        views.EcografiaDeleteView.as_view(),
        name='ecografia_delete'),
    url(r'^(?P<paciente_id>\d+)/editar-violencia-genero/$',
        views.ViolenciaGeneroUpdateCurrentView.as_view(),
        name='violencia_update'),
)

apps/pacientes/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns(
    '',
    url(
        r'^(?P<id>\d+)/$',
        views.PacienteDetailView.as_view(),
        name='detail'),
    url(
        r'^(?P<id>\d+)/editar/$',
        views.PacienteUpdateView.as_view(),
        name='update'),
    url(
        r'^(?P<id>\d+)/editar-control/$',
        views.PacienteControlUpdateView.as_view(),
        name='update_control'),
    url(
        r'^(?P<id>\d+)/antecedentes/$',
        views.PacienteAntecedentesDetailView.as_view(),
        name='antecedentes'),
    url(
        r'^(?P<id>\d+)/control-antecedentes/$',
        views.PacienteControlAntecedentesDetailView.as_view(),
        name='control_antecedentes'),
    url(
        r'^(?P<id>\d+)/antecedentes/editar/$',
        views.PacienteAntecedentesUpdateView.as_view(),
        name='antecedentes_edit'),
    url(
        r'^(?P<id>\d+)/control-antecedentes/editar/$',
        views.PacienteControlAntecedentesUpdateView.as_view(),
        name='control_antecedentes_edit'),
    url(
        r'^(?P<id>\d+)/antecedentes-familiares/$',
        views.AntecedentesFamiliaresView.as_view(),
        name='antecedentes_familiares_edit'),
    url(
        r'^(?P<id>\d+)/antecedentes-medicos/$',
        views.AntecedentesMedicosView.as_view(),
        name='antecedentes_medicos_edit'),
    url(
        r'^(?P<id>\d+)/antecedentes-resume-json',
        views.AntecedentesResumeJsonView.as_view(),
        name='antecedentes_resume_json'),
    url(
        r'^(?P<paciente_id>\d+)/crear-historia-clinica/$',
        views.HistoriaClinicaCreateView.as_view(),
        name='historia_clinica_create'),
    url(
        r'^registro/$',
        views.PacienteCreateView.as_view(),
        name='create'),
    url(
        r'^buscar/$',
        views.PacienteSearchView.as_view(),
        name='search'),
    url(
        r'^crear/(?P<id>\d+)$',
        views.PacienteCreateForce.as_view(),
        name='create_force'),
url(
        r'^crear-paciente-control/(?P<id>\d+)$',
        views.PacienteCreateForceUpdate.as_view(),
        name='create_force_update'),
)

wawared/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

handler403 = 'perfiles.views.handler_403'

admin.autodiscover()

urlpatterns = patterns(
    '',
    # Api
    url(r'^api/', include('api.urls', namespace='api')),
    # CIE
    url(r'^cie/', include('cie.urls', namespace='cie')),
    # CPT
    url(r'^cpt/', include('cpt.urls', namespace='cpt')),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Perfiles
    url(r'^', include('perfiles.urls')),
    # Dahboard
    url(r'^', include('dashboard.urls')),
    # Ubigeo
    url('^ubigeo/', include('ubigeo.urls', namespace='ubigeo')),
    # Gestantes
    url(r'^hce/', include('gestantes.urls', namespace='gestantes')),
    url(r'session_security/', include('session_security.urls')),
    # Dnireniec
    url(r'^dnireniec/', include('dnireniec.urls', namespace='dnireniec')),
    # Partos
    url(r'^partos/', include('partos.urls', namespace='partos')),
    # Firma
    url(r'^firma/', include('firma.urls', namespace='firma')),
    # Puerperio
    url(r'^puerperio/', include('puerperio.urls', namespace='puerperio')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/controles/templates/controles/controles.html
{% extends 'dashboard/base.html' %}
{% block title %}Atenciones{% endblock %}
{% block container %}
<div class="row">
    <div class="col-md-12">
        <div id="data">
            <form class="form-horizontal" role="form" method="post">
                {% csrf_token %}
                <div class="panel panel-default">
                    <div id="data-head" class="panel-heading">
                        <h3 class="panel-title">Atenciones prenatales embarazo actual</h3>
                    </div>
                    {% include 'embarazos/partials/control_paciente_resume_header.html' with paciente=paciente %}
                    <div class="panel-body">
                        <div class="col-sm-9 col-sm-offset-2">
                            <div class="btn-group">
                                {% if 'embarazos.change_embarazo' in user.get_all_permissions %}
                                <a class="btn btn-default" href="{% url 'embarazos:update_current' paciente.id %}">Editar embarazo actual</a>
                                {% endif %}
                                {% if 'embarazos.change_fichaviolenciafamiliar' in user.get_all_permissions %}
                                <a class="btn btn-default" href="{% url 'embarazos:violencia_update' paciente.id %}">Editar Violencia/Género</a>
                                {% endif %}
                                {% if 'controles.add_control' in user.get_all_permissions %}
                                <a class="btn btn-green" href="{% url 'controles:create' embarazo.id %}">Crear nueva atención</a>
                                {% endif %}
                                <a class="btn btn-default" href="{% url 'embarazos:ecografias' paciente.id %}">Ecografias</a>
                                <a class="btn btn-default" data-toggle="modal" href="#reports-modal">Reportes</a>
                                {% if 'embarazos.change_embarazo' in user.get_all_permissions %}
                                <a class="btn btn-danger" href="{% url 'embarazos:terminar_embarazo' paciente.id embarazo.id %}">Terminar embarazo</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="panel panel-default" id="data-buscar-body">
                            <table class="table table-bordered table-striped">
                                <thead class="panel-heading">
                                <tr>
                                    <th>#</th>
                                    <th>Fecha atención</th>
                                    <th>Próxima cita</th>
                                    <th>Edad gestacional en la atención</th>
                                    <th>Fecha probable del parto</th>
                                    <th>Establecimiento</th>
                                    <th>Opciones</th>
                                </tr>
                                </thead>
                                <tbody class="panel-body">
                                {% for control in controles %}
                                <tr>
                                    <td>{{ control.numero }}</td>
                                    <td>{{ control.atencion_fecha|date:'d/m/Y' }}</td>
                                    <td>{{ control.proxima_cita|date:'d/m/Y' }}</td>
                                    <!-- <td>{{ control.cita.fecha|date:'d/m/Y' }}</td> -->
                                    <td>{{ control.get_eg }}</td>
                                    <td>{{ control.fecha_probable_parto|date:'d/m/Y' }}</td>
                                    <td>{{ control.establecimiento.nombre }}</td>
                                    <td>
                                        {% if 'controles.change_control' in user.get_all_permissions %}
                                        <a class="btn btn-default" href="{% url 'controles:edit' control.id %}">Editar</a>
                                        {% else %}
                                        <a class="btn btn-default" href="{% url 'controles:detail' control.id %}">Ver detalle</a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="panel-footer">
                            <div class="pull-left">
                                {% if 'pacientes.change_paciente' in user.get_all_permissions %}
                                <a class="btn btn-default" href="{% url 'paciente:update' paciente.id %}">Ir al detalle de la paciente</a>
                                {% else %}
                                <a class="btn btn-default" href="{% url 'paciente:detail' paciente.id %}">Ir al detalle de la paciente</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="reports-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Reportes</h4>
            </div>
            <div class="modal-body">
                <div class="list-group">
                    <a class="list-group-item" href="{% url 'embarazos:reports:ficha_tamizaje' embarazo.id %}">Ficha de tamizaje de violencia</a>
                    <!-- <a class="list-group-item" href="{% url 'embarazos:reports:tamizaje_depresion' embarazo.id %}">Tamizaje depresión</a> -->
                    <!-- calculate with the last control -->
                    {% with embarazo.controles.last as last_control %}
                    {% if last_control %}
                    <a class="list-group-item" href="{% url 'controles:reports:solicitud_prueba_elisa' last_control.id %}">Solicitud prueba ELISA</a>
                    <a class="list-group-item" href="{% url 'controles:reports:solicitud_examen_citologico' last_control.id %}">Solicitud examen citológico</a>
                    <a class="list-group-item" href="{% url 'controles:reports:solicitud_examenes_clinicos' last_control.id %}">Solicitud examenes clínicos</a>
                    <div class="list-group-item">
                        <div class="row">
                            <span class="col-lg-5">Historia Clinica</span>
                            {% if historia_clinica_sign %}
                                <span class="col-lg-4">
                                    <a href="{% url 'controles:reports:historia_clinica' last_control.id 2 %}">
                                    <i class="glyphicon glyphicon-eye-open"></i>VER PDF FIRMADO
                                    </a>
                                </span>
                            {% else %}
                                <span class="col-lg-2">
                                    <a href="{% url 'controles:reports:historia_clinica' last_control.id %}">
                                    <i class="glyphicon glyphicon-eye-open"></i>VER PDF
                                    </a>
                                </span>
                                <span class="col-lg-2">
                                    <a href="{% url 'controles:reports:historia_clinica' last_control.id  1 %}">
                                    <i class="glyphicon glyphicon-lock"></i>Firmar
                                    </a>
                                </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="row">
                            <span class="col-lg-5">Plan parto</span>
                            {% if plan_parto_sign %}
                                <span class="col-lg-4">
                                    <a href="{% url 'controles:reports:plan_parto' last_control.id 2 %}">
                                    <i class="glyphicon glyphicon-eye-open"></i>VER PDF FIRMADO
                                    </a>
                                </span>
                            {% else %}
                                <span class="col-lg-2">
                                    <a href="{% url 'controles:reports:plan_parto' last_control.id %}">
                                    <i class="glyphicon glyphicon-eye-open"></i>VER PDF
                                    </a>
                                </span>
                                <span class="col-lg-2">
                                    <a href="{% url 'controles:reports:plan_parto' last_control.id  1 %}">
                                    <i class="glyphicon glyphicon-lock"></i>Firmar
                                    </a>
                                </span>
                            {% endif %}
                        </div>
                    </div>
                    <a class="list-group-item" href="{% url 'controles:reports:tarjeta_seguimiento' last_control.id %}">Tarjeta de seguimiento</a>
                    <a class="list-group-item" href="{% url 'controles:reports:receta_unica_estandarizada' last_control.id %}">Receta Única Estandarizada</a>
                    <a class="list-group-item" href="{% url 'controles:reports:receta_unica_flujo_vaginal' last_control.id %}">Receta Única Flujo Vaginal</a>
                    <a class="list-group-item" href="{% url 'controles:reports:receta_unica_prueba_rapida' last_control.id %}">Receta Única Prueba Rápida</a>
                    <a class="list-group-item" href="{% url 'controles:reports:hoja_referencia' last_control.id %}">Hoja de referencia</a>
                    <a class="list-group-item" href="{% url 'controles:reports:carne_control_prenatal' last_control.id %}">Carnet de Atención Prenatal</a>
                    <a class="list-group-item" href="{% url 'controles:reports:control_prenatal_excel' last_control.id %}">Atención prenatal</a>

                    {% if paciente.numero_documento %}
                        {% with paciente.tiene_seguro as seguro %}

                        {% if seguro %}
                            <a class="list-group-item" href="{% url 'controles:fua:009' last_control.id %}">Fua 009</a>
                            <a class="list-group-item" href="{% url 'controles:fua:011' last_control.id %}">Fua 011</a>
                            <a class="list-group-item" href="{% url 'controles:fua:013' last_control.id %}">Fua 013</a>
                            <a class="list-group-item" href="{% url 'controles:fua:024' last_control.id %}">Fua 024</a>
                            <a class="list-group-item" href="{% url 'controles:fua:071' last_control.id %}">Fua 071</a>

                        {% endif %}

                        {% endwith %}

                    {% endif %}
                    {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/controles/templates/controles/create.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}Crear control prenatal{% endblock %}
{% block extra_style %}
    <link href="{% static 'css/datepicker.css' %}" rel="stylesheet" media="screen">
{% endblock %}
{% block container %}
<div class="row">
    <div class="col-md-12">
        <div id="data">
            <form class="form-horizontal" name="form-control" id="form-control" role="form" method="post">
                {% csrf_token %}
                <div class="panel panel-default">
                    <div id="data-head" class="panel-heading">
                        <h3 class="panel-title">Crear Atención prenatal</h3>
                    </div>
                    {% include 'embarazos/partials/control_paciente_resume_header.html' with paciente=paciente %}
                    {% include 'controles/partials/control_form.html' with form=form %}
                    <div class="panel-footer">
                        <div class="pull-left">
                            <a class="btn btn-default" href="{% url 'controles:list' paciente.id %}">Regresar atenciones</a>
                        </div>

                        <div class="text-right">
                            <!--<button type="submit" class="ladda-button" data-color="blue" data-style="contract-overlay">
                                <span class="ladda-label">Guardar</span>
                                -->
                                 <input class="btn btn-green" type="submit" value="Guardar" id="btn-guardar"/>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block bottom_scripts %}
    {% include 'controles/partials/control_form_js.html' with embarazo=embarazo %}
{% endblock %}

apps/controles/templates/controles/edit.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}Editar control prenatal{% endblock %}
{% block extra_style %}
    <link href="{% static 'css/datepicker.css' %}" rel="stylesheet" media="screen">
{% endblock %}
{% block container %}
<div class="row">
    <div class="col-md-12">
        <div id="data">
            <form class="form-horizontal" name="form-control" id="form-control"  role="form" method="post">
                {% csrf_token %}
                <div class="panel panel-default">
                    <div id="data-head" class="panel-heading">
                        <h3 class="panel-title">Detalle de la atención prenatal</h3>
                    </div>
                    {% include 'embarazos/partials/paciente_resume_header.html' with paciente=paciente %}
                    {% include 'controles/partials/control_form.html' with form=form control=control %}
                    <div class="panel-footer">
                        <div class="pull-left">
                            <a class="btn btn-default" href="{% url 'controles:list' paciente.id %}">Regresar a las atenciones</a>
                        </div>
                        <div class="text-right">
                            <input class="btn btn-green" type="submit" value="Guardar" id="btn-guardar"/>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block bottom_scripts %}
    {% include 'controles/partials/control_form_js.html' with embarazo=embarazo %}
    {% if 'controles.change_control' not in user.get_all_permissions %}
    <script>
        $(document).ready(function(){ 
            $('input, select, textarea').prop('disabled', true);
        });
    </script>
    {% endif %}
{% endblock %}