apps/controles/urls.py
from django.conf.urls import patterns, url, include

import views

reports = patterns(
    '',
    url(
        r'^solicitud-examenes-clinicos/(?P<control_id>\d+)/$',
        views.SolicitudExamenesClinicosReportView.as_view(),
        name='solicitud_examenes_clinicos'),
    url(
        r'historia-clinica/(?P<control_id>\d+)/$',
        views.HistoriaClinicaReportView.as_view(),
        name='historia_clinica'),
    url(
        r'historia-clinica/(?P<control_id>\d+)/(?P<accion_id>\d+)/$',
        views.HistoriaClinicaReportView.as_view(),
        name='historia_clinica'),
    url(
        r'plan-parto/(?P<control_id>\d+)/$',
        views.PlanPartoReportView.as_view(),
        name='plan_parto'),
    url(
        r'plan-parto/(?P<control_id>\d+)/(?P<accion_id>\d+)/$',
        views.PlanPartoReportView.as_view(),
        name='plan_parto'),
    url(
        r'tarjeta-seguimiento/(?P<control_id>\d+)/$',
        views.TarjetaSeguimientoReportView.as_view(),
        name='tarjeta_seguimiento'),
    url(
        r'receta-unica-estandarizada/(?P<control_id>\d+)/$',
        views.RecetaUnicaEstandarizadaReportView.as_view(),
        name='receta_unica_estandarizada'),
    url(
        r'receta-unica-flujo-vaginal/(?P<control_id>\d+)/$',
        views.RecetaUnicaFlujoVaginalReportView.as_view(),
        name='receta_unica_flujo_vaginal'),
    url(
        r'receta-unica-prueba-rapida/(?P<control_id>\d+)/$',
        views.RecetaUnicaPruebaRapidaReportView.as_view(),
        name='receta_unica_prueba_rapida'),
    url(
        r'formato-unico-atencion/(?P<control_id>\d+)/$',
        views.FormatoUnicoAtencionReportView.as_view(),
        name='formato_unico_atencion'),
    url(
        r'hoja-referencia/(?P<control_id>\d+)/$',
        views.HojaReferenciaReportView.as_view(),
        name='hoja_referencia'),
    url(
        r'carne-control-prenatal/(?P<control_id>\d+)/$',
        views.CarneControlPrenatalReportView.as_view(),
        name='carne_control_prenatal'),
    url(
        r'^solicitud-examen-citologico/(?P<control_id>\d+)/$',
        views.SolicitudExamenCitologicoReportView.as_view(),
        name='solicitud_examen_citologico'),
    url(
        r'^solicitud-prueba-elisa/(?P<control_id>\d+)/$',
        views.SolicitudPruebaElisaReportView.as_view(),
        name='solicitud_prueba_elisa'),
    url(
        r'^control-prenatal-excel/(?P<control_id>\d+)/$',
        views.ControlPrenatalExcelReportView.as_view(),
        name='control_prenatal_excel'),
    url(
        r'^control-prenatal-excel/(?P<control_id>\d+)/(?P<accion_id>\d+)/$',
        views.ControlPrenatalExcelReportView.as_view(),
        name='control_prenatal_excel')
)

fua = patterns(
    '',
    url(
        r'^009/(?P<control_id>\d+)/$',
        views.Fua009ExcelReportView.as_view(),
        name='009'),
    url(
        r'^011/(?P<control_id>\d+)/$',
        views.Fua011ExcelReportView.as_view(),
        name='011'),
    url(
        r'^013/(?P<control_id>\d+)/$',
        views.Fua013ExcelReportView.as_view(),
        name='013'),
    url(
        r'^024/(?P<control_id>\d+)/$',
        views.Fua024ExcelReportView.as_view(),
        name='024'),
    url(
        r'^071/(?P<control_id>\d+)/$',
        views.Fua071ExcelReportView.as_view(),
        name='071'),
)

urlpatterns = patterns(
    '',
    url(r'^reportes/', include(reports, namespace='reports')),
    url(r'^fua/', include(fua, namespace='fua')),
    url(
        r'^(?P<paciente_id>\d+)/controles/$',
        views.ControlesView.as_view(),
        name='list'),
    url(
        r'^control/(?P<id>\d+)/$',
        views.ControlDetailView.as_view(),
        name='detail'),
    url(
        r'^control/(?P<id>\d+)/editar/$',
        views.ControlUpdateView.as_view(),
        name='edit'),
    url(
        r'^control/(?P<id>\d+)/eiminar/$',
        views.ControlDeleteView.as_view(),
        name='delete'),
    url(
        r'^control/(?P<id>\d+)/sintomas/$',
        views.SintomasDetailView.as_view(),
        name='sintomas_detail'),
    url(
        r'^control/(?P<id>\d+)/sintomas/edit/$',
        views.SintomasView.as_view(),
        name='sintomas'),
    url(
        r'^control/(?P<id>\d+)/diagnostico/$',
        views.DiagnosticoDetailView.as_view(),
        name='diagnostico_detail'),
    url(
        r'^control/(?P<id>\d+)/diagnostico/editar/$',
        views.DiagnosticoView.as_view(),
        name='diagnostico'),
    url(
        r'^control/(?P<id>\d+)/examen-fisico/$',
        views.ExamenFisicoDetailView.as_view(),
        name='examen_fisico_detail'),
    url(
        r'^control/(?P<id>\d+)/examen-fisico/editar/$',
        views.ExamenFisicoView.as_view(),
        name='examen_fisico'),
    url(
        r'^control/(?P<id>\d+)/laboratorio/$',
        views.LaboratorioDetailView.as_view(),
        name='laboratorio_detail'),
    url(
        r'^control/(?P<id>\d+)/laboratorio/editar/$',
        views.LaboratorioView.as_view(),
        name='laboratorio'),
    url(
        r'^(?P<embarazo_id>\d+)/crear-control/$',
        views.ControlCreateView.as_view(),
        name='create'),
    url(
        r'^control/(?P<id>\d+)/data/crecimiento-neonatal/$',
        views.DataCrecimientoNeonatalView.as_view(),
        name='data_crecimiento_neonatal'),
    url(
        r'^control/(?P<id>\d+)/data/altura-uterina/$',
        views.DataAlturaUterinaView.as_view(),
        name='data_altura_uterina'),
    url(
        r'^control/(?P<id>\d+)/data/ganancia-peso-materno/$',
        views.DataGananciaPesoMaternoView.as_view(),
        name='data_ganancia_peso_materno'),
)

apps/dashboard/urls.py
from django.conf.urls import patterns, url, include

import views

urlpatterns = patterns(
    '',
    url(r'^$', views.DashboardHomeView.as_view(), name='dashboard_home'),
    url(r'^paciente/', include('pacientes.urls', namespace='paciente')),
    url(r'^paciente/', include('embarazos.urls', namespace='embarazos')),
    url(r'^paciente/', include('controles.urls', namespace='controles')),
    url(
        r'^reportes-estadisticos/',
        include('indicadores.urls', namespace='indicadores')),
    url(r'^citas/', include('citas.urls', namespace='cita')),
    url(
        r'^establecimientos/',
        include('establecimientos.urls', namespace='establecimientos')),
)

apps/embarazos/urls.py
from django.conf.urls import patterns, url, include

import views

reports = patterns(
    '',
    url(r'^ficha-tamizaje/(?P<embarazo_id>\d+)/$',
        views.FichaTamizajeReportView.as_view(),
        name='ficha_tamizaje'),
    url(r'^ficha-tamizaje/(?P<embarazo_id>\d+)/(?P<accion_id>\d+)/$',
        views.FichaTamizajeReportView.as_view(),
        name='ficha_tamizaje'),
    url(r'^tamizaje-depresion/(?P<embarazo_id>\d+)/$',
        views.TamizajeDepresionReportView.as_view(),
        name='tamizaje_depresion'),
)

urlpatterns = patterns(
    '',
    url(r'^reportes/',
        include(reports, namespace='reports')),
    url(r'^(?P<paciente_id>\d+)/embarazos-previos/$',
        views.UltimosEmbarazosView.as_view(),
        name='ultimos_embarazos'),
    url(r'^(?P<paciente_id>\d+)/ecografias/$',
        views.EcografiasView.as_view(),
        name='ecografias'),
    url(r'^(?P<paciente_id>\d+)/agregar-ecografia/$',
        views.EcografiaCreateView.as_view(),
        name='ecografia_create'),
    url(r'^(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/editar/$',
        views.EcografiaUpdateView.as_view(),
        name='ecografia_edit'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo-previo/$',
        views.UltimoEmbarazoCreateView.as_view(),
        name='ultimo_embarazo_create'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/$',
        views.UltimoEmbarazoUpdateView.as_view(),
        name='ultimo_embarazo_edit'),
    url(r'^(?P<paciente_id>\d+)/embarazo-previo/(?P<id>\d+)/eliminar/$',
        views.UltimoEmbarazoDeleteView.as_view(),
        name='ultimo_embarazo_delete'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo/$',
        views.EmbarazoCreateView.as_view(),
        name='create'),
    url(r'^(?P<paciente_id>\d+)/registrar-control-embarazo/$',
        views.EmbarazoControlCreateView.as_view(),
        name='create-control-embarazo'),
    url(r'^(?P<paciente_id>\d+)/editar-embarazo-actual/$',
        views.EmbarazoUpdateCurrentView.as_view(),
        name='update_current'),
    url(r'^plan-de-parto/(?P<embarazo_id>\d+)/$',
        views.PlanPartoView.as_view(),
        name='plan_parto'),
    url(r'^plan-de-parto/(?P<embarazo_id>\d+)/edit/$',
        views.PlanPartoUpdateView.as_view(),
        name='plan_parto_edit'),
    url(r'^(?P<paciente_id>\d+)/terminar-embarazo/(?P<embarazo_id>\d+)/$',
        views.TerminarEmbarazoView.as_view(),
        name='terminar_embarazo'),
    url(r'^(?P<paciente_id>\d+)/registrar-embarazo-previo'
        r'/embarazo/(?P<embarazo_id>\d+)/$',
        views.UltimoEmbarazoFromEmbarazoCreateView.as_view(),
        name='ultimo_embarazo_from_embarazo_create'),
    url(r'^(?P<paciente_id>\d+)/ecografia/(?P<id>\d+)/eliminar/$',
        views.EcografiaDeleteView.as_view(),
        name='ecografia_delete'),
    url(r'^(?P<paciente_id>\d+)/editar-violencia-genero/$',
        views.ViolenciaGeneroUpdateCurrentView.as_view(),
        name='violencia_update'),
)

wawared/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

handler403 = 'perfiles.views.handler_403'

admin.autodiscover()

urlpatterns = patterns(
    '',
    # Api
    url(r'^api/', include('api.urls', namespace='api')),
    # CIE
    url(r'^cie/', include('cie.urls', namespace='cie')),
    # CPT
    url(r'^cpt/', include('cpt.urls', namespace='cpt')),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Perfiles
    url(r'^', include('perfiles.urls')),
    # Dahboard
    url(r'^', include('dashboard.urls')),
    # Ubigeo
    url('^ubigeo/', include('ubigeo.urls', namespace='ubigeo')),
    # Gestantes
    url(r'^hce/', include('gestantes.urls', namespace='gestantes')),
    url(r'session_security/', include('session_security.urls')),
    # Dnireniec
    url(r'^dnireniec/', include('dnireniec.urls', namespace='dnireniec')),
    # Partos
    url(r'^partos/', include('partos.urls', namespace='partos')),
    # Firma
    url(r'^firma/', include('firma.urls', namespace='firma')),
    # Puerperio
    url(r'^puerperio/', include('puerperio.urls', namespace='puerperio')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/controles/templates/controles/partials/control_nav.html
<div class="panel-body">
    <div class="col-sm-9 col-sm-offset-2">
        <div class="btn-group">
            {% if 'controles.change_control' in user.get_all_permissions %}
                <button class="btn btn-default btn-save-before"
                {% if 'sintomas' in request.path %}
                    style="background-color: green;color: white;"
                {% endif %}
                data-next-url="sintomas">Sintomas</button>
                <button class="btn btn-default btn-save-before"
                {% if 'fisico' in request.path %}
                    style="background-color: green;color: white;"
                {% endif %}
                data-next-url="examen_fisico">Examen Físico</button>
                <button class="btn btn-default btn-save-before"
                {% if 'laboratorio' in request.path %}
                    style="background-color: green;color: white;"
                {% endif %}
                data-next-url="laboratorio">Laboratorio</button>
                <button class="btn btn-default btn-save-before"
                {% if 'diagnostico' in request.path %}
                    style="background-color: green;color: white;"
                {% endif %}
                data-next-url="diagnostico">Diagnóstico</button>
                {% if 'embarazos.add_ecografia' in user.get_all_permissions %}
                <button class="btn btn-default btn-save-before" data-next-url="agregar_ecografia">Agregar ecografía</button>
                {% endif %}
            {% else %}
                <a class="btn btn-default"
                {% if 'sintomas' in request.path %}
                    style="background-color: green;color: white;"
                {% endif %}
                href="{% url 'controles:sintomas_detail' control.id %}">Sintomas</a>
                <a class="btn btn-default"
                {% if 'fisico' in request.path %}
                    style="background-color: green;color: white;"
                {% endif %}
                href="{% url 'controles:examen_fisico_detail' control.id %}">Examen Físico</a>
                <a class="btn btn-default"
                {% if 'laboratorio' in request.path %}
                    style="background-color: green;color: white;"
                {% endif %}
                href="{% url 'controles:laboratorio_detail' control.id %}">Laboratorio</a>
                <a class="btn btn-default"
                {% if 'diagnostico' in request.path %}
                    style="background-color: green;color: white;"
                {% endif %}
                href="{% url 'controles:diagnostico_detail' control.id %}">Diagnóstico</a>
                {% if 'embarazos.add_ecografia' in user.get_all_permissions %}
                <a class="btn btn-default" href="{% url 'embarazos:ecografia_create' control.id %}">Agregar ecografía</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>

apps/controles/templates/controles/partials/field_choices_as_tds.html
<td>
    {{ field.label }}
    {% for error in field.errors %}
    <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
</td>
{% for radio in field %}
{% if show_radio_label %}
    <td>{{ radio }}</td>
{% else %}
    <td class="text-center">{{ radio.tag }}</td>
{% endif %}
{% endfor %}